language: java

script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - "sudo apt-get install xclip xsel --no-install-recommends --yes"
  - sudo apt-get install pandoc
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh github_package ramnathv/slidify
  - ./travis-tool.sh github_package ramnathv/slidifyLibraries
  - ./travis-tool.sh github_package cboettig/knitcitations
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - DISPLAY=:99.0