language: java

script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github ramnathv/slidify@dev
  - ./travis-tool.sh install_github ramnathv/slidifyLibraries@dev
  - ./travis-tool.sh install_github cboettig/knitcitations
  - ./travis-tool.sh install_deps
  - "sudo apt-get install xclip xsel --no-install-recommends --yes"
  - sudo apt-get install pandoc
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--resave-data=best" 
    - R_CHECK_ARGS="--as-cran"
    - DISPLAY=:99.0
